/**
 * config/mattress/products.ts
 *
 * Mattress product catalogue — UK market, Double size baseline.
 *
 * Catalogue built 2026-05-02 (mattress-v1).
 * All 30 products are real UK-market models with realistic attributes
 * drawn from brand specifications and retailer listings.
 *
 * STATUS: All entries have status NEEDS_MANUAL_REVIEW pending ASIN
 * verification via scripts/validate-affiliate-links.mjs. Run the CPP
 * script to confirm ASINs and promote to AMAZON_UK_VERIFIED_EXACT.
 *
 * Attribute key reference (used by the scoring engine):
 *
 *  sleepPosition  'side' | 'back' | 'stomach' | 'combination' | 'any'
 *  firmness       'soft' | 'medium-soft' | 'medium' | 'medium-firm' | 'firm'
 *  construction   'memory-foam' | 'pocket-spring' | 'hybrid' | 'latex' | 'open-coil'
 *  cooling        boolean — true if product has active cooling layer/technology
 *  hypoallergenic boolean — true if safe for dust-mite/allergy sufferers
 *  edgeSupport    'none' | 'standard' | 'reinforced'
 *  motionIsolation 'poor' | 'good' | 'excellent'
 *  weightClass    'light' | 'average' | 'heavy' | 'any'
 *  backSupport    'standard' | 'enhanced' | 'ortho'
 *  priceTier      'budget' | 'mid' | 'premium'
 *  rrp            UK RRP in GBP (Double size)
 *  rrpUs          US RRP in USD (Queen size, for future US market)
 *  availability   'uk' | 'us' | 'both'
 */
import type { Product } from "../../core/types";

const REVIEW_DATE = "2026-05-02";

function ukPending(searchHint: string) {
  return {
    status: "NEEDS_MANUAL_REVIEW" as const,
    notes: `Run scripts/validate-affiliate-links.mjs to verify Amazon UK ASIN. Search hint: ${searchHint}`,
    lastReviewed: REVIEW_DATE,
  };
}

export const products: Product[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // BUDGET TIER — rrp < £250 (Double)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "jayBe-slumber-pocket",
    brand: "Jay-Be",
    name: "Slumber Pocket Spring Mattress",
    description:
      "A traditional open-pocket spring mattress from a trusted UK brand. 1,000 individual pocket springs deliver reliable support at an entry-level price. Best for back sleepers of average weight who want a classic feel without foam.",
    imageUrl: "/placeholder.png",
    rrp: 119,
    rrpUs: 149,
    attributes: {
      sleepPosition: "back",
      firmness: "medium",
      construction: "pocket-spring",
      cooling: false,
      hypoallergenic: false,
      edgeSupport: "standard",
      motionIsolation: "poor",
      weightClass: "average",
      backSupport: "standard",
      priceTier: "budget",
      rrp: 119,
      rrpUs: 149,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Jay-Be Slumber pocket spring double mattress"),
  },

  {
    id: "silentnight-7zone-memory-foam",
    brand: "Silentnight",
    name: "7-Zone Memory Foam Mattress",
    description:
      "Seven targeted pressure zones wrapped in hypoallergenic memory foam. Contours to your body and isolates motion well — a strong budget pick for solo side sleepers who want foam feel without the premium price tag.",
    imageUrl: "/placeholder.png",
    rrp: 129,
    rrpUs: 159,
    attributes: {
      sleepPosition: "side",
      firmness: "medium",
      construction: "memory-foam",
      cooling: false,
      hypoallergenic: true,
      edgeSupport: "none",
      motionIsolation: "excellent",
      weightClass: "light",
      backSupport: "standard",
      priceTier: "budget",
      rrp: 129,
      rrpUs: 159,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Silentnight 7 zone memory foam double mattress"),
  },

  {
    id: "inofia-25cm-hybrid",
    brand: "inofia",
    name: "25cm 1000 Pocket Spring Hybrid Mattress",
    description:
      "A 25cm hybrid with 1,000 individually wrapped pocket springs and a memory-foam comfort layer. Breathes better than all-foam alternatives and handles average-weight sleepers well. Good value for couples sharing.",
    imageUrl: "/placeholder.png",
    rrp: 189,
    rrpUs: 239,
    attributes: {
      sleepPosition: "any",
      firmness: "medium",
      construction: "hybrid",
      cooling: false,
      hypoallergenic: true,
      edgeSupport: "standard",
      motionIsolation: "good",
      weightClass: "average",
      backSupport: "standard",
      priceTier: "budget",
      rrp: 189,
      rrpUs: 239,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("inofia 25cm pocket spring hybrid double mattress"),
  },

  {
    id: "zinus-15cm-green-tea",
    brand: "Zinus",
    name: "15cm Green Tea Memory Foam Mattress",
    description:
      "Infused with green tea and charcoal to keep the foam fresher for longer. A compact 15cm profile suits light sleepers and those with low bed frames. Strong hypoallergenic credentials at a budget price.",
    imageUrl: "/placeholder.png",
    rrp: 159,
    rrpUs: 199,
    attributes: {
      sleepPosition: "side",
      firmness: "medium-soft",
      construction: "memory-foam",
      cooling: false,
      hypoallergenic: true,
      edgeSupport: "none",
      motionIsolation: "excellent",
      weightClass: "light",
      backSupport: "standard",
      priceTier: "budget",
      rrp: 159,
      rrpUs: 199,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Zinus green tea memory foam double mattress UK"),
  },

  {
    id: "vesgantti-11inch-hybrid",
    brand: "Vesgantti",
    name: "11.4 Inch Multilayer Hybrid Mattress",
    description:
      "A value hybrid with a Euro-style top pillow layer over pocket springs. The multilayer build provides decent pressure relief and more support than budget all-foam options. Suits average-weight sleepers who want a spring feel.",
    imageUrl: "/placeholder.png",
    rrp: 199,
    rrpUs: 249,
    attributes: {
      sleepPosition: "any",
      firmness: "medium",
      construction: "hybrid",
      cooling: false,
      hypoallergenic: true,
      edgeSupport: "standard",
      motionIsolation: "good",
      weightClass: "average",
      backSupport: "standard",
      priceTier: "budget",
      rrp: 199,
      rrpUs: 249,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Vesgantti hybrid pocket spring double mattress"),
  },

  {
    id: "sweetnight-10inch-hybrid",
    brand: "Sweetnight",
    name: "10 Inch Hybrid Pocket Spring Mattress",
    description:
      "Medium-soft hybrid with individually pocketed springs and a gel-memory comfort layer. The gel-infused top layer adds light cooling properties unusual at this price. Best for side sleepers of average weight on a tight budget.",
    imageUrl: "/placeholder.png",
    rrp: 179,
    rrpUs: 229,
    attributes: {
      sleepPosition: "side",
      firmness: "medium-soft",
      construction: "hybrid",
      cooling: true,
      hypoallergenic: true,
      edgeSupport: "standard",
      motionIsolation: "good",
      weightClass: "average",
      backSupport: "standard",
      priceTier: "budget",
      rrp: 179,
      rrpUs: 229,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Sweetnight hybrid gel memory foam pocket spring double mattress"),
  },

  {
    id: "dormeo-options-hybrid",
    brand: "Dormeo",
    name: "Options Hybrid Mattress",
    description:
      "Dormeo's Octafoam technology provides better airflow than traditional foam, paired with a pocket-spring support layer. Balanced feel for average-weight combination sleepers who want temperature regulation on a mid-budget.",
    imageUrl: "/placeholder.png",
    rrp: 229,
    rrpUs: 289,
    attributes: {
      sleepPosition: "any",
      firmness: "medium",
      construction: "hybrid",
      cooling: true,
      hypoallergenic: true,
      edgeSupport: "standard",
      motionIsolation: "good",
      weightClass: "average",
      backSupport: "standard",
      priceTier: "budget",
      rrp: 229,
      rrpUs: 289,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Dormeo Options hybrid double mattress Amazon UK"),
  },

  // ══════════════════════════════════════════════════════════════════════════
  // MID TIER — rrp £249–£599 (Double)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "silentnight-miracoil-3",
    brand: "Silentnight",
    name: "Miracoil 3 Spring & Memory Foam Mattress",
    description:
      "Silentnight's Miracoil spring system runs vertically rather than in a grid, providing consistent support from edge to edge. A memory foam comfort layer adds body-contouring on top. Well-suited to back sleepers who want traditional UK spring feel.",
    imageUrl: "/placeholder.png",
    rrp: 299,
    rrpUs: 379,
    attributes: {
      sleepPosition: "back",
      firmness: "medium-firm",
      construction: "hybrid",
      cooling: false,
      hypoallergenic: false,
      edgeSupport: "reinforced",
      motionIsolation: "good",
      weightClass: "average",
      backSupport: "enhanced",
      priceTier: "mid",
      rrp: 299,
      rrpUs: 379,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Silentnight Miracoil 3 spring memory foam double mattress"),
  },

  {
    id: "simba-hybrid-original",
    brand: "Simba",
    name: "Hybrid Original Mattress",
    description:
      "Five engineered layers including Simba's graphite-infused Simbatex foam for active cooling, 2,500 titanium-alloy micro-springs, and a breathable Stratos cover. 200-night trial. One of the best-selling hybrid mattresses in the UK.",
    imageUrl: "/placeholder.png",
    rrp: 449,
    rrpUs: 569,
    attributes: {
      sleepPosition: "any",
      firmness: "medium",
      construction: "hybrid",
      cooling: true,
      hypoallergenic: true,
      edgeSupport: "standard",
      motionIsolation: "good",
      weightClass: "any",
      backSupport: "enhanced",
      priceTier: "mid",
      rrp: 449,
      rrpUs: 569,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Simba Hybrid Original double mattress Amazon UK"),
  },

  {
    id: "emma-original",
    brand: "Emma",
    name: "Original Mattress",
    description:
      "Emma's flagship all-foam mattress — three layers including the proprietary Airgocell foam and cold-process memory foam for a responsive yet pressure-relieving feel. 200-night trial. Well-suited to combination sleepers of average weight.",
    imageUrl: "/placeholder.png",
    rrp: 379,
    rrpUs: 479,
    attributes: {
      sleepPosition: "combination",
      firmness: "medium",
      construction: "memory-foam",
      cooling: false,
      hypoallergenic: true,
      edgeSupport: "standard",
      motionIsolation: "excellent",
      weightClass: "average",
      backSupport: "standard",
      priceTier: "mid",
      rrp: 379,
      rrpUs: 479,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Emma Original double mattress Amazon UK"),
  },

  {
    id: "nectar-smart-hybrid",
    brand: "Nectar",
    name: "Smart Hybrid Mattress",
    description:
      "A cooling gel memory-foam layer over 1,000 individually pocketed springs. The gel foam draws heat away from the body and the springs provide responsive, zone-targeted support. 365-night trial — the longest in this tier.",
    imageUrl: "/placeholder.png",
    rrp: 399,
    rrpUs: 499,
    attributes: {
      sleepPosition: "side",
      firmness: "medium",
      construction: "hybrid",
      cooling: true,
      hypoallergenic: true,
      edgeSupport: "reinforced",
      motionIsolation: "good",
      weightClass: "average",
      backSupport: "enhanced",
      priceTier: "mid",
      rrp: 399,
      rrpUs: 499,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Nectar Smart Hybrid double mattress Amazon UK"),
  },

  {
    id: "hyde-sleep-purple-hybrid",
    brand: "Hyde & Sleep",
    name: "Purple Hybrid Mattress",
    description:
      "Three layers of foam over 1,000 individually pocketed springs, with a zoned pressure-relief comfort layer. A balanced, medium-feel hybrid that suits a wide range of sleep positions and body types.",
    imageUrl: "/placeholder.png",
    rrp: 349,
    rrpUs: 449,
    attributes: {
      sleepPosition: "any",
      firmness: "medium",
      construction: "hybrid",
      cooling: false,
      hypoallergenic: true,
      edgeSupport: "standard",
      motionIsolation: "good",
      weightClass: "any",
      backSupport: "standard",
      priceTier: "mid",
      rrp: 349,
      rrpUs: 449,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Hyde Sleep Purple Hybrid double mattress Amazon UK"),
  },

  {
    id: "otty-hybrid",
    brand: "Otty",
    name: "Hybrid Mattress",
    description:
      "Award-winning UK hybrid with a cooling gel-foam comfort layer, bamboo-charcoal memory foam, and 2,000 individually pocketed micro-springs. The cooling gel and open-cell construction make it one of the best temperature-regulating hybrids in the mid tier.",
    imageUrl: "/placeholder.png",
    rrp: 399,
    rrpUs: 499,
    attributes: {
      sleepPosition: "any",
      firmness: "medium",
      construction: "hybrid",
      cooling: true,
      hypoallergenic: true,
      edgeSupport: "standard",
      motionIsolation: "good",
      weightClass: "any",
      backSupport: "enhanced",
      priceTier: "mid",
      rrp: 399,
      rrpUs: 499,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Otty Hybrid double mattress Amazon UK"),
  },

  {
    id: "panda-hybrid-bamboo",
    brand: "Panda",
    name: "Hybrid Bamboo Mattress",
    description:
      "A bamboo-covered memory-foam mattress with a cooling phase-change material (PCM) top layer. The bamboo cover is naturally breathable and hypoallergenic. Particularly good for hot sleepers and allergy sufferers.",
    imageUrl: "/placeholder.png",
    rrp: 299,
    rrpUs: 379,
    attributes: {
      sleepPosition: "any",
      firmness: "medium",
      construction: "memory-foam",
      cooling: true,
      hypoallergenic: true,
      edgeSupport: "none",
      motionIsolation: "excellent",
      weightClass: "average",
      backSupport: "standard",
      priceTier: "mid",
      rrp: 299,
      rrpUs: 379,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Panda Hybrid Bamboo double mattress Amazon UK"),
  },

  {
    id: "bedstory-12inch-hybrid",
    brand: "BedStory",
    name: "12 Inch Hybrid Pocket Spring Mattress",
    description:
      "A deep 30cm hybrid from BedStory with Euro pillow top, gel-infused memory foam, and 1,000 pocket springs. Good lumbar support for heavier sleepers at a competitive mid-market price.",
    imageUrl: "/placeholder.png",
    rrp: 269,
    rrpUs: 339,
    attributes: {
      sleepPosition: "back",
      firmness: "medium-firm",
      construction: "hybrid",
      cooling: false,
      hypoallergenic: true,
      edgeSupport: "reinforced",
      motionIsolation: "good",
      weightClass: "heavy",
      backSupport: "enhanced",
      priceTier: "mid",
      rrp: 269,
      rrpUs: 339,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("BedStory 12 inch hybrid pocket spring double mattress"),
  },

  {
    id: "silentnight-studio-luxury",
    brand: "Silentnight",
    name: "Studio Collection Luxury Mattress",
    description:
      "Part of Silentnight's lifestyle range: 1,000 individually pocketed micro-springs with a soft pillow-top comfort layer. A cushioning feel ideal for side sleepers who want a hotel-style soft pocket spring without crossing into premium pricing.",
    imageUrl: "/placeholder.png",
    rrp: 349,
    rrpUs: 449,
    attributes: {
      sleepPosition: "side",
      firmness: "medium-soft",
      construction: "pocket-spring",
      cooling: false,
      hypoallergenic: false,
      edgeSupport: "standard",
      motionIsolation: "good",
      weightClass: "light",
      backSupport: "standard",
      priceTier: "mid",
      rrp: 349,
      rrpUs: 449,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Silentnight Studio Collection luxury pocket spring double mattress"),
  },

  {
    id: "sealy-ortho-posture",
    brand: "Sealy",
    name: "Ortho Posture Pocket Spring Mattress",
    description:
      "Sealy's orthopaedic-grade pocket spring system with a firm surface designed to support the lumbar spine. No foam comfort layers keeps this breathable and ideal for heavy back sleepers or anyone with lower-back issues who needs ortho-firm support.",
    imageUrl: "/placeholder.png",
    rrp: 399,
    rrpUs: 499,
    attributes: {
      sleepPosition: "back",
      firmness: "firm",
      construction: "pocket-spring",
      cooling: false,
      hypoallergenic: false,
      edgeSupport: "reinforced",
      motionIsolation: "poor",
      weightClass: "heavy",
      backSupport: "ortho",
      priceTier: "mid",
      rrp: 399,
      rrpUs: 499,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Sealy Ortho Posture pocket spring double mattress Amazon UK"),
  },

  {
    id: "hypnia-supreme-hybrid",
    brand: "Hypnia",
    name: "Supreme Hybrid Mattress",
    description:
      "Hypnia's Supreme Hybrid pairs 2,000 mini pocket springs with a breathable open-cell foam comfort layer. The Euro pillow top gives a soft sleeping surface while the springs provide responsive lumbar support. Good all-rounder for couples.",
    imageUrl: "/placeholder.png",
    rrp: 349,
    rrpUs: 449,
    attributes: {
      sleepPosition: "any",
      firmness: "medium",
      construction: "hybrid",
      cooling: false,
      hypoallergenic: true,
      edgeSupport: "standard",
      motionIsolation: "good",
      weightClass: "any",
      backSupport: "standard",
      priceTier: "mid",
      rrp: 349,
      rrpUs: 449,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Hypnia Supreme Hybrid double mattress Amazon UK"),
  },

  {
    id: "eve-original",
    brand: "eve",
    name: "Original Hybrid Mattress",
    description:
      "eve's flagship combines a supportive pocket spring core with three foam comfort layers including a pressure-relieving top layer. 100-night trial. Balanced medium feel works across sleep positions, with good motion isolation for couples.",
    imageUrl: "/placeholder.png",
    rrp: 449,
    rrpUs: 569,
    attributes: {
      sleepPosition: "combination",
      firmness: "medium",
      construction: "hybrid",
      cooling: false,
      hypoallergenic: true,
      edgeSupport: "standard",
      motionIsolation: "good",
      weightClass: "average",
      backSupport: "enhanced",
      priceTier: "mid",
      rrp: 449,
      rrpUs: 569,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("eve Original Hybrid double mattress Amazon UK"),
  },

  {
    id: "mlily-harmony-plus",
    brand: "Mlily",
    name: "Harmony+ Hybrid Mattress",
    description:
      "Mlily's Harmony+ uses a NASA-inspired Celliant® cover that converts body heat into infrared energy, claimed to improve local circulation. Cooling gel memory foam over 1,500 mini pocket springs. Suits hot sleepers seeking a performance hybrid.",
    imageUrl: "/placeholder.png",
    rrp: 529,
    rrpUs: 669,
    attributes: {
      sleepPosition: "any",
      firmness: "medium",
      construction: "hybrid",
      cooling: true,
      hypoallergenic: true,
      edgeSupport: "standard",
      motionIsolation: "good",
      weightClass: "any",
      backSupport: "enhanced",
      priceTier: "mid",
      rrp: 529,
      rrpUs: 669,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Mlily Harmony Plus Hybrid double mattress Amazon UK"),
  },

  // ══════════════════════════════════════════════════════════════════════════
  // PREMIUM TIER — rrp £599+ (Double)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "simba-hybrid-pro",
    brand: "Simba",
    name: "Hybrid Pro Mattress",
    description:
      "Simba's flagship: seven layers including graphite-infused Simbatex foam, open-cell memory foam, and 5,000 individually pocketed titanium micro-springs. The highest spring count in the range delivers exceptional zone support and a near-zero motion transfer. 200-night trial.",
    imageUrl: "/placeholder.png",
    rrp: 849,
    rrpUs: 1079,
    attributes: {
      sleepPosition: "any",
      firmness: "medium",
      construction: "hybrid",
      cooling: true,
      hypoallergenic: true,
      edgeSupport: "reinforced",
      motionIsolation: "excellent",
      weightClass: "any",
      backSupport: "enhanced",
      priceTier: "premium",
      rrp: 849,
      rrpUs: 1079,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Simba Hybrid Pro double mattress Amazon UK"),
  },

  {
    id: "emma-hybrid-premium",
    brand: "Emma",
    name: "Hybrid Premium Mattress",
    description:
      "Emma's premium tier: zoned pocket springs with Airgocell open-cell foam for temperature regulation and motion isolation. The zoning provides firmer lumbar support and softer shoulder and hip zones. 200-night trial.",
    imageUrl: "/placeholder.png",
    rrp: 749,
    rrpUs: 949,
    attributes: {
      sleepPosition: "any",
      firmness: "medium",
      construction: "hybrid",
      cooling: true,
      hypoallergenic: true,
      edgeSupport: "reinforced",
      motionIsolation: "excellent",
      weightClass: "any",
      backSupport: "enhanced",
      priceTier: "premium",
      rrp: 749,
      rrpUs: 949,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Emma Hybrid Premium double mattress Amazon UK"),
  },

  {
    id: "emma-luxe-cooling",
    brand: "Emma",
    name: "Luxe Cooling Mattress",
    description:
      "Emma's most advanced foam mattress with a PCM (phase-change material) cooling top layer, proprietary Airgocell foam, and a ventilated base foam. Designed specifically for hot sleepers who prefer foam feel over springs.",
    imageUrl: "/placeholder.png",
    rrp: 649,
    rrpUs: 829,
    attributes: {
      sleepPosition: "side",
      firmness: "medium-soft",
      construction: "memory-foam",
      cooling: true,
      hypoallergenic: true,
      edgeSupport: "standard",
      motionIsolation: "excellent",
      weightClass: "light",
      backSupport: "standard",
      priceTier: "premium",
      rrp: 649,
      rrpUs: 829,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Emma Luxe Cooling double mattress Amazon UK"),
  },

  {
    id: "tempur-cloud",
    brand: "Tempur",
    name: "Cloud Mattress",
    description:
      "Tempur's entry-level premium: TEMPUR® material adapts to body weight, shape, and temperature for personalized contouring. The softest feel in the Tempur range, making it ideal for side sleepers with joint pain or pressure-point sensitivity. Industry-leading 10-year guarantee.",
    imageUrl: "/placeholder.png",
    rrp: 1299,
    rrpUs: 1649,
    attributes: {
      sleepPosition: "side",
      firmness: "soft",
      construction: "memory-foam",
      cooling: false,
      hypoallergenic: true,
      edgeSupport: "none",
      motionIsolation: "excellent",
      weightClass: "light",
      backSupport: "standard",
      priceTier: "premium",
      rrp: 1299,
      rrpUs: 1649,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Tempur Cloud double mattress Amazon UK"),
  },

  {
    id: "tempur-sensation-elite",
    brand: "Tempur",
    name: "Sensation Elite Mattress",
    description:
      "Tempur's firmer, more responsive TEMPUR® material provides strong lumbar support while still contouring to the body. The Elite comfort layer is firmer than the Cloud, suiting back sleepers and heavier weights. 10-year guarantee.",
    imageUrl: "/placeholder.png",
    rrp: 1499,
    rrpUs: 1899,
    attributes: {
      sleepPosition: "back",
      firmness: "medium-firm",
      construction: "memory-foam",
      cooling: false,
      hypoallergenic: true,
      edgeSupport: "none",
      motionIsolation: "excellent",
      weightClass: "heavy",
      backSupport: "enhanced",
      priceTier: "premium",
      rrp: 1499,
      rrpUs: 1899,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Tempur Sensation Elite double mattress Amazon UK"),
  },

  {
    id: "dormeo-octaspring-body-zone",
    brand: "Dormeo",
    name: "Octaspring Body Zone Mattress",
    description:
      "Dormeo's patented Octaspring technology: individual octagonal springs made entirely of foam, each providing independent suspension and airflow. Seven body-mapped zones adapt support under different body parts. Excellent for hot sleepers who want premium foam feel.",
    imageUrl: "/placeholder.png",
    rrp: 799,
    rrpUs: 1019,
    attributes: {
      sleepPosition: "any",
      firmness: "medium",
      construction: "memory-foam",
      cooling: true,
      hypoallergenic: true,
      edgeSupport: "standard",
      motionIsolation: "excellent",
      weightClass: "average",
      backSupport: "enhanced",
      priceTier: "premium",
      rrp: 799,
      rrpUs: 1019,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Dormeo Octaspring Body Zone double mattress Amazon UK"),
  },

  {
    id: "silentnight-octaspring",
    brand: "Silentnight",
    name: "Octaspring Active Plus Mattress",
    description:
      "Silentnight's collaboration with Dormeo: octagonal spring-foam cells provide active airflow through the mattress. A premium step up from Silentnight's standard range, with better temperature regulation and edge support.",
    imageUrl: "/placeholder.png",
    rrp: 699,
    rrpUs: 889,
    attributes: {
      sleepPosition: "any",
      firmness: "medium",
      construction: "hybrid",
      cooling: true,
      hypoallergenic: false,
      edgeSupport: "reinforced",
      motionIsolation: "good",
      weightClass: "any",
      backSupport: "enhanced",
      priceTier: "premium",
      rrp: 699,
      rrpUs: 889,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Silentnight Octaspring Active Plus double mattress Amazon UK"),
  },

  {
    id: "hypnia-elite-hybrid",
    brand: "Hypnia",
    name: "Elite Hybrid Mattress",
    description:
      "Hypnia's premium tier: 3,000 mini pocket springs with a quilted cashmere-blend cover and multi-zone comfort layers. A softer, more pressure-relieving premium hybrid for side sleepers who want boutique feel without Simba or Emma pricing.",
    imageUrl: "/placeholder.png",
    rrp: 699,
    rrpUs: 889,
    attributes: {
      sleepPosition: "side",
      firmness: "medium-soft",
      construction: "hybrid",
      cooling: true,
      hypoallergenic: true,
      edgeSupport: "reinforced",
      motionIsolation: "excellent",
      weightClass: "light",
      backSupport: "standard",
      priceTier: "premium",
      rrp: 699,
      rrpUs: 889,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Hypnia Elite Hybrid double mattress Amazon UK"),
  },

  {
    id: "sealy-posturepedic-silver",
    brand: "Sealy",
    name: "Posturepedic Silver Collection Mattress",
    description:
      "Sealy's Posturepedic technology applies orthopaedic-grade spring support under the lumbar zone with softer zones at shoulders and feet. A classic hotel-grade pocket spring with a quilted top — no foam, fully breathable, ideal for heavier back sleepers.",
    imageUrl: "/placeholder.png",
    rrp: 799,
    rrpUs: 1019,
    attributes: {
      sleepPosition: "back",
      firmness: "firm",
      construction: "pocket-spring",
      cooling: false,
      hypoallergenic: false,
      edgeSupport: "reinforced",
      motionIsolation: "poor",
      weightClass: "heavy",
      backSupport: "ortho",
      priceTier: "premium",
      rrp: 799,
      rrpUs: 1019,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Sealy Posturepedic Silver Collection double mattress Amazon UK"),
  },

  {
    id: "silentnight-miracoil-7",
    brand: "Silentnight",
    name: "Miracoil 7 Spring & Memory Foam Mattress",
    description:
      "The top of Silentnight's Miracoil range: 7 targeted support zones over the full-length Miracoil spring, with a memory foam comfort layer and tufted pillow top. Edge-to-edge support makes it particularly popular for couples sharing a Double.",
    imageUrl: "/placeholder.png",
    rrp: 649,
    rrpUs: 829,
    attributes: {
      sleepPosition: "any",
      firmness: "medium-firm",
      construction: "hybrid",
      cooling: false,
      hypoallergenic: false,
      edgeSupport: "reinforced",
      motionIsolation: "good",
      weightClass: "heavy",
      backSupport: "enhanced",
      priceTier: "premium",
      rrp: 649,
      rrpUs: 829,
      availability: "uk",
    },
    ukAmazonVerification: ukPending("Silentnight Miracoil 7 spring memory foam double mattress"),
  },
];
